version: "3"
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql
    env_file:
      - config.env
    ports:
        - "127.0.0.1:5432:5432"
    deploy:
      resources:
        limits:
          memory: 4G

  app:
    build: app/
    restart: always
    ports:
      - 1337:1337
    depends_on:
      - db
    links:
      - db
    env_file:
      - config.env
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G